name: InitGrounder_1
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=23.3
  - numpy=1.23
  - scipy=1.9
  - mkl=2023.1.0
  - mkl-service
  - numba=0.56
  - llvmlite=0.39
  - networkx=2.8
  - joblib=1.2
  - gensim=4.3
  - cudatoolkit=11.2
  - cudnn=8.1.0
  - pip:
      - tensorflow==2.10.*
      - protobuf<3.20
      - typing-extensions<5
      - h5py>=3.7,<3.9
      - tqdm